
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team02-f24-10
owner: ucsb-cs156-f24
repo_name: team02-f24-10
pull_requests: [{"author":{"id":"MDQ6VXNlcjI1MzQwNzk1","is_bot":false,"login":"AjayLiu","name":"AjayLiu"},"headRefName":"ajay-articles-fixtures","number":63,"title":"Added articlesFixtures.js","url":"https://github.com/ucsb-cs156-f24/team02-f24-10/pull/63"},{"author":{"id":"U_kgDOBtxmHw","is_bot":false,"login":"justinwu13","name":"Justin Wu"},"headRefName":"Justin-UCSBDiningCommonsMenuItem-backend","number":62,"title":"Add team01 files for UCSBDiningCommonsMenuItem","url":"https://github.com/ucsb-cs156-f24/team02-f24-10/pull/62"}]
