
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team02-f24-10
owner: ucsb-cs156-f24
repo_name: team02-f24-10
pull_requests: [{"author":{"id":"MDQ6VXNlcjcyODQwNDQz","is_bot":false,"login":"rranu","name":"Rajvir Ranu"},"headRefName":"rr-51-editpage-helpreq","number":126,"title":"HelpRequest - EditPage","url":"https://github.com/ucsb-cs156-f24/team02-f24-10/pull/126"},{"author":{"id":"MDQ6VXNlcjcyODQwNDQz","is_bot":false,"login":"rranu","name":"Rajvir Ranu"},"headRefName":"rr-50-indexpage-helpreq","number":125,"title":"HelpRequest - IndexPage","url":"https://github.com/ucsb-cs156-f24/team02-f24-10/pull/125"},{"author":{"id":"MDQ6VXNlcjcyODQwNDQz","is_bot":false,"login":"rranu","name":"Rajvir Ranu"},"headRefName":"rr-49-createpage-helpreq","number":124,"title":"HelpRequests - CreatePage","url":"https://github.com/ucsb-cs156-f24/team02-f24-10/pull/124"},{"author":{"id":"MDQ6VXNlcjcyODQwNDQz","is_bot":false,"login":"rranu","name":"Rajvir Ranu"},"headRefName":"rr-48-placeholders-helpreq","number":123,"title":"HelpRequests PlaceHolder Pages","url":"https://github.com/ucsb-cs156-f24/team02-f24-10/pull/123"}]
