
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team02-f24-10
owner: ucsb-cs156-f24
repo_name: team02-f24-10
pull_requests: [{"author":{"id":"MDQ6VXNlcjU0NTQ2OTYx","is_bot":false,"login":"gargAneesh","name":"Aneesh"},"headRefName":"ag-30-recreqs-copyPlaceholders","number":105,"title":"Ag 30 recreqs copy placeholders","url":"https://github.com/ucsb-cs156-f24/team02-f24-10/pull/105"},{"author":{"id":"U_kgDOBtxmHw","is_bot":false,"login":"justinwu13","name":"Justin Wu"},"headRefName":"jw-97-end2end-menuitem","number":104,"title":"Add end-to-end tests for UCSBDiningCommonsMenuItem","url":"https://github.com/ucsb-cs156-f24/team02-f24-10/pull/104"},{"author":{"id":"MDQ6VXNlcjU0NTQ2OTYx","is_bot":false,"login":"gargAneesh","name":"Aneesh"},"headRefName":"ag-29-recreqs-tableComp","number":103,"title":"Ag 29 recreqs table comp","url":"https://github.com/ucsb-cs156-f24/team02-f24-10/pull/103"},{"author":{"id":"U_kgDOBtxmHw","is_bot":false,"login":"justinwu13","name":"Justin Wu"},"headRefName":"jw-96-int-tests-menuitem","number":102,"title":"Add integration tests for UCSBDiningCommonsMenuItem","url":"https://github.com/ucsb-cs156-f24/team02-f24-10/pull/102"},{"author":{"id":"MDQ6VXNlcjMzNzMyMzky","is_bot":false,"login":"r0ckwav3","name":"Peter"},"headRefName":"pv-98-integration-test-orgs","number":101,"title":"Create Integration tests for UCSBOrganizations","url":"https://github.com/ucsb-cs156-f24/team02-f24-10/pull/101"},{"author":{"id":"MDQ6VXNlcjcyODQwNDQz","is_bot":false,"login":"rranu","name":"Rajvir Ranu"},"headRefName":"rr-45-fixtures-helpreq","number":100,"title":"Wrote fixtures for helpRequests","url":"https://github.com/ucsb-cs156-f24/team02-f24-10/pull/100"}]
