
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team02-f24-10
owner: ucsb-cs156-f24
repo_name: team02-f24-10
pull_requests: [{"author":{"id":"MDQ6VXNlcjU0NTQ2OTYx","is_bot":false,"login":"gargAneesh","name":"Aneesh"},"headRefName":"ag-114-recreqs-WebIT","number":116,"title":"Recommendation Requests - E2E Tests","url":"https://github.com/ucsb-cs156-f24/team02-f24-10/pull/116"},{"author":{"id":"MDQ6VXNlcjU0NTQ2OTYx","is_bot":false,"login":"gargAneesh","name":"Aneesh"},"headRefName":"ag-113-recreqs-intTests","number":115,"title":"Recommendation Requests - Integration Tests","url":"https://github.com/ucsb-cs156-f24/team02-f24-10/pull/115"},{"author":{"id":"U_kgDOBtnxJw","is_bot":false,"login":"DderrickLee","name":""},"headRefName":"DL-42-MIREditPage","number":112,"title":"Added Edit Page to MenuItemReview","url":"https://github.com/ucsb-cs156-f24/team02-f24-10/pull/112"}]
